name: Build and Publish baresip Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-baresip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push baresip image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./baresip/Dockerfile.build-from-source
          push: true
          tags: |
            ghcr.io/andyweiss/baresip:${{ github.ref_name }}
            ghcr.io/andyweiss/baresip:latest
